version: '3.3'
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'card_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldata:/var/lib/mysql
      - "./database/data/1_base_schema.sql:/docker-entrypoint-initdb.d/1_base_schema.sql"
      - "./database/data/2_initial_data.sql:/docker-entrypoint-initdb.d/2_initial_data.sql"
volumes:
  mysqldata: